server.port=8080
spring.application.name=underwater

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://Gustavo:G1043978518g@underwater.geenwvy.mongodb.net/Datos?retryWrites=true&w=majority

# Multipart — subida de imágenes hasta 10MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB

# Carpeta donde se guardan las imágenes
app.upload.dir=/app/uploads/productos

# Logging
logging.level.com.underwater=DEBUG